version: '3.7'
#x-aws-vpc: "vpc-0891ce638950f3414"
services:
  database:
    container_name: postgres
    image: postgres:13
    environment:  # or use env_file 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: localhost     
      POSTGRES_PORT: 5432
      POSTGRES_DB: school  
    volumes:
      - postgres-data:/var/lib/postgresql/data
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:  # or use env_file 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: database     # This is the name of the database service in this file above
      POSTGRES_PORT: 5432
      POSTGRES_DB: school 
    expose:
      - 8081
    depends_on:
      - database
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - flask
    restart: always
    environment:
      DOMAINS: 'test.shawaracourseapp.com => https://test.shawaracourseapp.com'
      # STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'
volumes:
  postgres-data:
